# A dockerized stack for development
version: '3.3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "ENVIRONMENT=apiserver,dev"
      - "MYSQL_DB_URI=osmt:password@db:3306"
      - "ELASTICSEARCH_URI=elasticsearch:9200"
      - "REDIS_URI=redis:6379"
    depends_on:
      - db
      - elasticsearch
      - redis
    ports:
      - "8080:8080"
    networks:
      - osmt

  db:
    image: library/mysql:8.0
    volumes:
      - osmt_sql_db:/var/lib/mysql:rw
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_PASSWORD=password"
      - "MYSQL_HOST=0.0.0.0"
      - "MYSQL_DATABASE=osmt_db"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_USER=osmt"
    ports:
      - 3306:3306
    networks:
      - osmt

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "net=host"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - osmt

  redis:
    image: library/redis:6.0.6
    networks:
      - osmt
    ports:
      - 6379:6379

networks:
  osmt:
    driver: bridge

volumes:
  osmt_sql_db:
  elastic_data:
