apiVersion: v1
kind: Service
metadata:
  name: nginx-elb
  labels:
    app: nginx-elb
spec:
  type: LoadBalancer
  selector:
    app: osmt-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: "http"
    - port: 443
      protocol: TCP
      targetPort: 443
      name: "https"