# A dockerized stack for development
# execute with `docker-compose -f dev-stack.yml up`
version: '3.3'
services:
  db:
    image: library/mysql:5.7
    volumes:
      - osmt_sql_db:/var/lib/mysql:rw
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_PASSWORD=password"
      - "MYSQL_HOST=0.0.0.0"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_USER=user"
    ports:
      - 3306:3306
    networks:
      - osmt

networks:
  osmt:
    driver: bridge

volumes:
  osmt_sql_db:
