openapi: 3.0.0
info:
  version: 0.6.0
  title: OSMT API
  description: Draft API for the Open Skills Management Toolset (MVP)
security:
  - bearerAuth: []

paths:
  /api/skills/search:
    post:
      tags:
        - Skills
      summary: Search for skills
      description: Find Rich Skill Descriptors matching the query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SkillSearchDescriptor'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Skill'
  /api/skills:
    get:
      summary: Get all skills
      description: Return all skills in the library
      parameters:
        - in: query
          name: per_page
          description: maximum number of skills to return per page
          default: 100
          schema:
            type: number
        - in: query
          name: page
          description: page number to return
          default: 1
          schema:
            type: number
      responses:
        '200':
          description: OK
          headers:
            Link: 
              $ref: '#/components/headers/Link'
            X-Total-Count:
              $ref: '#/components/headers/XTotalCount'
            X-RateLimit-Limit:
              $ref: '#/components/headers/XRateLimit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/XRateRemaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/XRateReset'

          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skill'
            text/csv:
              schema:
                type: string
                example: >-
                  id,type,author,skillName,skillStatement,alignments,keywords,category,occupations

                  https://osmt.example.com/skills/9cd84455-2086-4f41-bcac-6d518beeb6ac, RichSkillDescriptor, "https://osmt.example.com/organization", "Document Saving", "The learner copies and saves documents to their local machine.", "https://skillsource.example.com/base-skills/simple-compuhacking", "documents, file operations, computer basics", "Productivity Software", "13-0000, 13-2000, 13-2010, 13-2030, 13-2040, 13-2060, 13-2080"
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResult'
      tags:
        - Skills
    post:
      tags:
        - Skills
      summary: Create skills
      description: Define one or more new Rich Skill Descriptors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Skill'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Skill'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'

  /api/skills/{uuid}:
    parameters:
      - name: uuid
        in: path
        description: uuid of skill
        required: true
        schema:
          type: string
    get: 
      tags:
        - Skills
      summary: Retrieve a skill 
      description: >-
        Return the full information about a Rich Skill Descriptor
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Skill'
            text/html:
              schema:
                type: string
                example: A human readable description of the skill
    post:
      tags:
        - Skills
      summary: Update a skill
      description: Update information in an existing Rich Skill Descriptor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SkillUpdateDescriptor'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Skill'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'

  /api/collections/search:
    post:
      tags:
        - Collections
      summary: Search for collections
      description: Find collections matching the query

  /api/collections:
    get:
      tags:
        - Collections
      summary: Get all collections
      description: Retrieve all the collections
    post:
      tags:
        - Collections
      summary: Create a collection
      description: Define a new collection


  /api/collections/{uuid}:
    parameters:
      - name: uuid
        in: path
        description: Collection UUID
        required: true
        schema:
          type: string
    get:
      tags:
        - Collections
      summary: Retrieve a collection
      description: Retrieve all the information about a collection
    post:
      tags:
        - Collections
      summary: Update a collection
      description: Update an existing collection 
    delete:
      tags:
        - Collections
      summary: Destroy a collection
      description: Permanently destroy a collection.  This operation can not be un-done.

  /api/collections/{uuid}/skills:
    parameters:
      - name: uuid
        in: path
        description: Collection UUID
        required: true
        schema:
          type: string
    get:
      tags:
        - Collections
      summary: Retrieve the skills in a collection
      description: Retrieve all the information about skills in a collection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Skill'


  /api/tasks/{uuid}:
    parameters:
      - name: uuid
        in: path
        description: Task uuid
        required: true
        schema:
          type: string
    get:
      summary: Check the results of a task
      description: Return the results of a previously requested task, or its status if not complete yet
      responses:
        '200':
          description: OK - Returns the results of the task in the content-type originally requested.
          content:
            '*/*':
              description: "The results of the previously requested task"
        '202':
          description: Accepted - Returns the status of the in-progress Task.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResult'
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/XRateLimit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/XRateRemaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/XRateReset'
      tags:
        - Tasks



components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  headers:
    Link: 
      type: string
      description: |
        Links to related resources in 
        [RFC 5988](https://tools.ietf.org/html/rfc5988#section-5) format.
        This will include a link with relation type `next` or `prev` if present.
    XTotalCount:
      type: string
      description: |
        The total number of records returned on all pages for this request.
    XRateLimit:
      type: number
      description: |
        The number of requests permitted to make per hour.
    XRateRemaining:
      type: number
      description: |
        The number of requests remaining in the current rate limit window.
    XRateReset:
      type: string
      description: |
        The time at which the current rate limit window resets in UTC epoch seconds.
  schemas:
    Skill:
      type: object
      required:
        - skillName
        - skillStatement
      properties:
        id:
          type: string
          format: uri
          readOnly: true
        type:
          type: '"RichSkillDescriptor"'
          readOnly: true
        uuid:
          type: string
          format: uuid
          readOnly: true
        status:
          type: string
          enum: ["draft","published","archived"]
          default: draft
        skillName: 
          type: string
        skillStatement:
          type: string
        category:
          type: string
        keywords:
          type: array
          items: 
            type: string
        alignments:
          type: array
          items:
            type: string
            format: uri
        certifications:
          type: array
          items:
            type: string
            format: uri
        occupations:
          type: array
          items:
            type: string
            format: job code
        employers:
          type: array
          items:
            type: string
        skillsEmbodied:
          type: array
          items:
            type: string
        author:
          type: string
          format: uri

      example:
        id: https://osmt.example.com/skills/9cd84455-2086-4f41-bcac-6d518beeb6ac
        type: RichSkillDescriptor
        author: https://osmt.example.com/organization
        status: published
        skillName: Document Saving
        skillStatement: The learner copies and saves documents to their local machine.
        alignments: 
          - "https://skillsource.example.com/base-skills/simple-compuhacking"
        keywords: 
          - "documents"
          - "file operations"
          - "computer basics"
        category: "Productivity Software"
        occupations: 
          - "13-0000"
          - "13-2000"
          - "13-2010"
          - "13-2030"
          - "13-2040"
          - "13-2060"
          - "13-2080"
    SkillUpdateDescriptor:
      type: object
      properties:
        skillUuid:  
          type: string
          format: uuid
        skillName: 
          type: string
        skillStatement:
          type: string
        status:
          type: string
          enum: ["draft","published","archived"]
        category:
          type: string
        keywords:
          type: array
          items:
            $ref: '#/components/schemas/ListUpdateDescriptor'
        alignments:
          type: array
          items:
            $ref: '#/components/schemas/ListUpdateDescriptor'
        certifications:
          type: array
          items:
            $ref: '#/components/schemas/ListUpdateDescriptor'
        occupations:
          type: array
          items:
            $ref: '#/components/schemas/ListUpdateDescriptor'
        employers:
          type: array
          items:
            $ref: '#/components/schemas/ListUpdateDescriptor'
        skillsEmbodied:
          type: array
          items:
            $ref: '#/components/schemas/ListUpdateDescriptor'
        author:
          type: string
          format: uri
      example:
        skillName: "New Skill Name"
        keywords: 
          - operation: add
            name: "Added Keyword"
          - operation: remove
            name: "Removed Keyword"
        occupation:
          - operation: add
            name: "11-9013"
    ListUpdateDescriptor:
      type: object
      properties:
        operation:
          type: string
          enum: ["add", "remove"]
        name:
          type: string
    SkillSearchDescriptor:
      type: object
      properties:
        skillName: 
          type: string
        skillStatement:
          type: string
        status:
          type: string
          enum: ["draft","published","archived"]
          default: draft
        category:
          type: string
        keywords:
          type: array
          items: 
            type: string
        alignments:
          type: array
          items:
            type: string
            format: uri
        certifications:
          type: array
          items:
            type: string
            format: uri
        occupations:
          type: array
          items:
            type: string
            format: job code
        employers:
          type: array
          items:
            type: string
        skillsEmbodied:
          type: array
          items:
            type: string
        author:
          type: string
          format: uri

    Collection:
      type: object
      properties:      
        name: 
          type: string
        description: 
          type: string
        skills: 
          type: array
          items:
            type: string
            format: uri
    TaskResult:
      type: object
      properties:
        href: 
          type: string
          format: uri
        uuid:
          type: string
          format: uuid
          readOnly: true
        content-type:
          type: string
        status:
          type: string
          enum: ["Processing","Ready"]
      example:
        href: "/tasks/3fa85f64-5717-4562-b3fc-2c963f66afa6"
        uuid: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        content-type: "text/csv"
        status: "Processing"
    ErrorResult:
      type: object
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              field:
                type: string





